os:
  - linux
  - osx

language: cpp
sudo: required

compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MtVy/218swleJaw4KTB/LpBohQedFFjSvdXW74fXyM0UkDSKKVoU8IROyr5V/wsvAZRqX7NvDimmOSshh6l1U3psOb4J1/etfhrWWbotDkpWTeI/5eYnkXqHevy0hCxjCo9REjckBLFeYVLA/C2fmlv0KqW+zinDujuDetPGTII="

script:
  - cmake .
  - make -kj2

before_install:
  - if [ "${TRAVIS_BRANCH}" == "coverity_scan" ]; then echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi

addons:
  apt:
    packages: 
      - libsdl2-dev 
      - libsdl2-mixer-dev 
      - libsdl2-image-dev 
      - libglew-dev 
      - libglm-dev 
      - mesa-common-dev
  homebrew:
    packages: 
      - sdl2 
      - sdl2_mixer 
      - sdl2_image 
      - glew 
      - glm
    update: true
  coverity_scan:
    project:
      name: "JanSimek/falltergeist"
      description: "Fallout 2 open-source engine"
    build_command_prepend: "cmake -H. -B_builds"
    build_command: "cmake --build _builds"
    branch_pattern: coverity_scan

# Deploy to GitHub pages
#deploy:
#  provider: script
#  script: ./gh-pages-deploy.sh
#  skip_cleanup: true
#  on:
#    branch: master
#    condition: "$GHPAGES_DEPLOY = yes"